name: Branch Sync

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  sync_branches:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "{{ secrets.PERSONAL_EMAIL }}"

      - name: Merge main into develop
        run: |
          git checkout develop
          git merge --no-edit main
          git push origin develop
