name: Branch Sync

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  sync_branches:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "${{ secrets.PERSONAL_EMAIL }}"

      - name: Merge main into develop
        run: |
          git checkout develop
          git merge --no-edit main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Sync develop with main"
          body: "Automatically syncing develop branch with main after a PR has been merged."
          branch: "sync-develop-with-main"
          base: "develop"
          token: ${{ secrets.GITHUB_TOKEN }}
